### PR TITLE
Fuerte devel

### PR DESCRIPTION
**Pull request by MarkusEich**
Adapted package to work with ROS Fuerte

### CODE REVIEW

**Comment by wjwwood** [comment]
Looks like I cannot automatically merge this, it usually means there is an unresolved conflict? can you rebase against this this repository's `fuerte-devel`?

Should be something like this:

``` bash
$ git checkout fuerte-devel
$ git remote add upstream https://github.com/ros-perception/pcl_conversions.git
$ git fetch upstream
$ git rebase upstream/fuerte-devel
$ git push -f origin fuerte-devel
```

**Comment by MarkusEich** [comment]
I updated the repo. I had to rebase it on hydro, because the groovy branch
did not compile. can now be pulled .

**Comment by wjwwood** [comment]
I'll have to merge this manually, rebasing onto hydro-devel wouldn't work, as my fuerte-devel branch is a fork off of groovy-devel.

**Comment by wjwwood** [comment]
I set this repositories `fuerte-devel` branch to match yours.

**Pull request merged**
