### PR TITLE
Fix timestamp round error in hydro-devel

### PR DESCRIPTION
**Pull request by garaemon**
https://github.com/ros-perception/pcl_conversions/pull/15 patch for hydro branch

### CODE REVIEW

**Comment by paulbovbel** [comment]
LGTM, @LucidOne ?

**Comment by LucidOne** [comment]
Seem good, but I can't test it today.

**Comment by garaemon** [comment]
Please merge this and release new version.

Because pcl_ros and [depth_image_proc](https://github.com/ros-perception/image_pipeline/blob/hydro-devel/depth_image_proc/src/nodelets/point_cloud_xyz.cpp#L107) are affected by this bug.

**Comment by garaemon** [comment]
Could you release newer version including this patch?

**Pull request merged**
